[package]
name = "oauth_client"
version = "0.1.0"
edition = "2021"


[dependencies]
rand = "0.8"
sha2 = "0.10"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "2.0"
dotenv = "0.15"